version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clock
      POSTGRES_PASSWORD: clock123

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URL: 'postgresql://clock:clock123@postgres:5432/clock'
      PYTHONUNBUFFERED: 0
    volumes:
      - ./startup.sh:/app/startup.sh
      - ./app:/app
    depends_on:
      - postgres
    links:
      - postgres:postgres
    working_dir: /app
    entrypoint: ["./startup.sh"]